/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppMeetingsRouteImport } from './routes/_app.meetings'
import { Route as AppMeetingsIdRouteImport } from './routes/_app.meetings.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsIdRoute = AppMeetingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMeetingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/meetings': typeof AppMeetingsRouteWithChildren
  '/meetings/$id': typeof AppMeetingsIdRoute
}
export interface FileRoutesByTo {
  '/meetings': typeof AppMeetingsRouteWithChildren
  '/': typeof AppIndexRoute
  '/meetings/$id': typeof AppMeetingsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/meetings': typeof AppMeetingsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/meetings/$id': typeof AppMeetingsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/meetings' | '/meetings/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/meetings' | '/' | '/meetings/$id'
  id: '__root__' | '/_app' | '/_app/meetings' | '/_app/' | '/_app/meetings/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings': {
      id: '/_app/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings/$id': {
      id: '/_app/meetings/$id'
      path: '/$id'
      fullPath: '/meetings/$id'
      preLoaderRoute: typeof AppMeetingsIdRouteImport
      parentRoute: typeof AppMeetingsRoute
    }
  }
}

interface AppMeetingsRouteChildren {
  AppMeetingsIdRoute: typeof AppMeetingsIdRoute
}

const AppMeetingsRouteChildren: AppMeetingsRouteChildren = {
  AppMeetingsIdRoute: AppMeetingsIdRoute,
}

const AppMeetingsRouteWithChildren = AppMeetingsRoute._addFileChildren(
  AppMeetingsRouteChildren,
)

interface AppRouteChildren {
  AppMeetingsRoute: typeof AppMeetingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMeetingsRoute: AppMeetingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
